### PR TITLE
Full Width Function Add

### PR DESCRIPTION
**Pull request by xfl03**
when "width":0 it will be automatic fill the width of window

### CODE REVIEW

**Comment by AlexIIL** [comment]
This looks interesting. I'm just going to test it a bit first before merging though :)

**Comment by AlexIIL** [comment]
Out of interest, why do you close the Java splash screen? I haven't seen it in vanilla minecraft before, so why did you include it?

**Comment by xfl03** [comment]
I am sorry I do not know why the commit after pulling request is pulled to your project. :(
But the reason why I close the splash screen is awt can auto close it, but opengl does not, so i fix this bug in this mod.

**Comment by AlexIIL** [comment]
Ok. By the way any commits you make to the same branch as the pull request are also part of the pull request- so you can fix things if they are not quite right

**Comment by AlexIIL** [comment]
Seems to be working fine and well.

**Comment by xfl03** [comment]
Thanks for your merge. If it can be OK, could I pull the same request in this mod for 1.8?

**Comment by AlexIIL** [comment]
Yes please. Although pull to the 1.3.x branch, as it won't be required 
in 1.4.x going forward (you can use a function to specify width, so you 
can just type "screenwidth" and it will make it the width of the screen).

Although it would probably be helpful to have the SplashScreen java fix 
on the main branch.

**Pull request merged**
